<?php

use Drupal\Component\Serialization\Json;
use Drupal\Core\Database\Database;

/**
 * Implements hook_page_attachments().
 */
function mars_newsletter_page_attachments(array &$page) {
  $data_layer_service = \Drupal::service('mars_newsletter.data_layer_service');
  $data = $data_layer_service->getData();
  if (!empty($data)) {
    $page['#attached']['html_head'][] = [[
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => "window.dataLayer = window.dataLayer || []; dataLayer.push({'event': 'newsletterSignupForm', 'formValues': " . Json::encode($data) . "});",
    ],
      'mars_newsletter_data_layer',
    ];
  }
}

/**
 * Implements hook_theme().
 */
function mars_newsletter_theme($existing, $type, $theme, $path) {
   return [
      'mars_newsletter_signup_form' => [
         'variables' => [
            'webform_newsletter' => [],
            'webform_block_label' => NULL,
            'text_color_override' => NULL,
            'background_color' => NULL,
         ],
         'template' => 'mars-newsletter-signup-form',
      ],
      'mars_newsletter_email_signup_form' => [
         'variables' => [
            'webform_newsletter' => [],
            'webform_block_label' => NULL,
            'newsletter_toggle' => NULL,
            'newsletter_bg_color' => NULL,
            'override_white_color' => NULL,
         ],
         'template' => 'mars-newsletter-email-signup-form',
      ],
   ];
}

/**
 * Implements hook_form_alter().
 */
function mars_newsletter_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $form['#attached']['library'][] = 'mars_newsletter/newsletter_signup';
    $config_factory = \Drupal::configFactory();
    $config = $config_factory->getEditable('mars_newsletter_form.settings')->get('newsletter.config_form');
    $form['#attached']['drupalSettings']['mars_newsletter']['required_field_message'] = !empty($config['field_required_message']) ? $config['field_required_message'] : t('This field is required');
    $form['#attached']['drupalSettings']['mars_newsletter']['email_validation_message'] = !empty($config['email_validation_message']) ? $config['email_validation_message'] : t('Enter valid email ID');
    $form['#attached']['drupalSettings']['mars_newsletter']['success_message'] = !empty($config['success_message']) ? $config['success_message'] : t('Your subcription is successfull');
  return $form;
}

/**
 * Implements hook__update_9001().
 */
function mars_newsletter_update_9001() {
  $schema = [
    'description' => 'Stores all webform submission data.',
    'fields' => [
      'webform_id' => [
        'description' => 'The webform id.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
      ],
      'sid' => [
        'description' => 'The webform submission id.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
      ],
    ],
  ];
  Database::getConnection()->schema()->createTable('webform_submission', $schema);
}
