theme_styles: 'twix'
default_link_content: 'See details'
link_content: BUY NOW2
# recipe_is_new: true;

item:
  card_url: https://storybook.js.org/
  card__image__src: image9@3x.png
  paragraph_content: 'TWIX® PEANUT BUTTER Minis'
  product_card_link_attributes: []
  default_link_attributes:
    'target': '_self'
    'href': 'https://storybook.js.org/'

  link_url: ''
product_sku: 123456
show_rating_and_reviews: true
wtb_commerce_vendor: 'commerce_connector'
wtb_button_type: 'my_own'
wtb_widget_id: 123321
datalayer_taxonomy: 'taxonomy vocabylary: term;'
