theme_styles: 'twix'
default_link_content: 'See details'
link_content: BUY NOW2

item:
  card_url: https://storybook.js.org/
  card__image__src: image9@3x.png
  paragraph_content: 'TWIX® PEANUT BUTTER Minis'
  default_link_attributes:
    'target': '_self'
    'href': 'https://storybook.js.org/'
  link_url: ''
