<?php

/**
 * @file
 * MARS Entry gate module main file.
 */

/**
 * Implements hook_theme().
 */
function mars_entry_gate_theme($existing, $type, $theme, $path) {
  return [
    'entry_gate' => [
      'variables' => [
        'title' => '',
        'description' => '',
        'heading' => '',
        'marketing_message' => '',
        'minimum_age' => '',
        'error_title' => '',
        'error_message' => '',
        'error_link_1' => '',
        'error_link_2' => '',
      ],
      'template' => 'entry-gate',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mars_entry_gate_preprocess_page(&$variables) {
  $config = \Drupal::config('mars_entry_gate.settings');

  if ($variables['is_admin'] || !$config || !$config->get('enabled')) {
    return;
  }

  $keys = [
    'title',
    'description',
    'heading',
    'marketing_message',
    'minimum_age',
    'error_title',
    'error_message',
    'error_link_1',
    'error_link_2',
  ];

  $entry_gate_render_array = [
    '#theme' => 'entry_gate',
    '#cache' => [
      'tags' => ['config:mars_entry_gate.settings'],
    ],
  ];

  foreach ($keys as $key) {
    $entry_gate_render_array['#' . $key] = $config->get($key) ?? '';
  }

  $variables['page']['content']['entry_gate'] = $entry_gate_render_array;
}
