<?php

/**
 * @file
 * MARS Entry gate module main file.
 */

use Drupal\mars_common\Traits\OverrideThemeTextColorTrait;

/**
 * Implements hook_theme().
 */
function mars_entry_gate_theme($existing, $type, $theme, $path) {
  return [
    'entry_gate' => [
      'variables' => [
        'title' => '',
        'description' => '',
        'heading' => '',
        'marketing_message' => '',
        'minimum_age' => '',
        'error_title' => '',
        'error_message' => '',
        'error_link_1' => '',
        'error_link_2' => '',
        'brand_shape' => '',
        'text_color_override' => NULL,
      ],
      'template' => 'entry-gate',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mars_entry_gate_preprocess_html(&$variables) {
  $config = Drupal::config('mars_entry_gate.settings');
  $text_color_override = FALSE;
  if (!empty($config->get('override_text_color')['override_color'])) {
    $text_color_override = OverrideThemeTextColorTrait::$overrideColor;
  }

  $variables['#cache']['tags'][] = 'config:mars_entry_gate.settings';

  if ($variables['is_admin'] || !$config || !$config->get('enabled')) {
    return;
  }

  $keys = [
    'title',
    'description',
    'heading',
    'marketing_message',
    'minimum_age',
    'error_title',
    'error_message',
    'error_link_1',
    'error_link_2',
  ];

  $entry_gate_render_array = [
    '#theme' => 'entry_gate',
    '#text_color_override' => $text_color_override,
  ];

  foreach ($keys as $key) {
    $entry_gate_render_array['#' . $key] = $config->get($key) ?? '';
  }

  /** @var \Drupal\mars_common\ThemeConfiguratorParser $theme_configurator */
  $theme_configurator = Drupal::service('mars_common.theme_configurator_parser');
  $entry_gate_render_array['#brand_shape'] = $theme_configurator->getBrandShapeWithoutFill();

  $variables['page_bottom']['entry_gate'] = $entry_gate_render_array;
}
