<?php

/**
 * @file
 * MARS Search module main file.
 */

use Drupal\entityqueue\EntitySubqueueInterface;
use Drupal\search_api\IndexInterface;

/**
 * Implements hook_update_dependencies().
 */
function mars_search_update_dependencies() {
  $dependencies['search_api_solr'][8200] = [
    'mars_search' => 8003,
  ];
  $dependencies['search_api_solr'][8331] = [
    'mars_search' => 8004,
  ];
  $dependencies['search_api_solr'][8409] = [
    'mars_search' => 8005,
  ];
  return $dependencies;
}

/**
 * Implements hook_theme().
 */
function mars_search_theme($existing, $type, $theme, $path) {
  return [
    'mars_search_suggestions' => [
      'variables' => [
        'suggestions' => [],
        'show_all' => [],
        'empty_text' => NULL,
        'empty_text_description' => NULL,
        'no_results' => NULL,
        'cards_view' => NULL,
      ],
    ],
    'mars_search_header' => [
      'variables' => [
        'search_header_heading' => NULL,
        'brand_border' => NULL,
        'brand_shape' => NULL,
        'input_form' => NULL,
        'search_filters' => NULL,
        'filter_title_transform' => NULL,
      ],
      'template' => 'mars-search-header',
    ],
    'mars_search_no_results' => [
      'variables' => [
        'no_results_links' => NULL,
        'no_results_text' => NULL,
        'no_results_heading' => NULL,
        'graphic_divider' => NULL,
      ],
      'template' => 'mars-search-no-results',
    ],
    'mars_search_faq_block' => [
      'variables' => [
        'faq_filter_toggle' => NULL,
        'faq_title' => NULL,
        'faq_ques_label' => NULL,
        'faq_ans_label' => NULL,
        'input_form' => NULL,
        'facets' => NULL,
        'items' => [],
        'cta_button_label' => NULL,
        'cta_button_link' => NULL,
        'search_result_counter' => NULL,
        'search_result_text' => NULL,
        'data_layer' => NULL,
        'no_results_heading' => NULL,
        'no_results_text' => NULL,
        'graphic_divider' => NULL,
      ],
    ],
    'mars_search_faq_item' => [
      'variables' => [
        'content' => NULL,
        'faq_ques_label' => NULL,
        'faq_ans_label' => NULL,
        'li_base_class' => NULL,
        'li_modifiers' => NULL,
        'li_blockname' => NULL,
      ],
    ],
    'mars_search_search_results_block' => [
      'variables' => [
        'items' => [],
        'theme_styles' => '',
        'graphic_divider' => NULL,
        'filters' => [],
        'applied_filters_list' => [],
        'ajax_card_grid_heading' => NULL,
        'ajax_card_grid_link_text' => NULL,
        'ajax_card_grid_link_attributes' => [],
        'ajax_card_grid_border_radius' => NULL,
        'data_layer' => NULL,
        'no_results' => NULL,
        'results_key_header' => NULL,
        'grid_modifiers' => NULL,
        'filter_title_transform' => NULL,
        'text_color_override' => NULL,
        'override_filter_title_color' => NULL,
      ],
    ],
    'mars_search_grid_block' => [
      'variables' => [
        'items' => [],
        'filters' => [],
        'applied_filters_list' => [],
        'input_form' => [],
        'theme_styles' => '',
        'graphic_divider' => NULL,
        'brand_border' => NULL,
        'ajax_card_grid_heading' => NULL,
        'ajax_card_grid_link_text' => NULL,
        'ajax_card_grid_link_attributes' => [],
        'ajax_card_grid_border_radius' => NULL,
        'data_layer' => NULL,
        'no_results' => NULL,
        'grid_modifiers' => NULL,
        'filter_title_transform' => NULL,
        'text_color_override' => NULL,
        'override_filter_title_color' => NULL,
        'overlaps_previous' => NULL,
      ],
    ],
    'mars_search_filter' => [
      'variables' => [
        'filters' => [],
        'applied_filters_list' => [],
        'input_form' => [],
        'filter_title_transform' => NULL,
      ],
    ],
    'mars_search_type_filter' => [
      'variables' => [
        'search_results' => [],
        'filter_title_transform' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_search_api_index_items_alter().
 */
function mars_search_search_api_index_items_alter(IndexInterface $index, array &$items) {
  /** @var Drupal\search_api\Item\Item $item */
  foreach ($items as $item) {
    /** @var Drupal\Core\Entity\Plugin\DataType\EntityAdapter $object */
    $object = $item->getOriginalObject();

    $type = $object->get('type')->target_id;
    if ($type == 'product_multipack') {
      $object->set('type', 'product');
    }
    $item->setOriginalObject($object);
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for entity_subqueue entities.
 */
function mars_search_entity_subqueue_presave(EntitySubqueueInterface $queue) {
  // Looping through all queue items.
  foreach ($queue->get('items')->referencedEntities() as $node) {
    // This is needed for search_api_entity_update().
    $node->original = clone $node;
    // Re-indexing items.
    search_api_entity_update($node);
  }
}
