<?php

/**
 * @file
 * MARS Search module main file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;


/**
 * Implements hook_theme().
 */
function mars_search_theme($existing, $type, $theme, $path) {
  return [
    'mars_search_suggestions' => [
      'variables' => [
        'suggestions' => [],
        'show_all' => NULL,
        'empty_text' => NULL,
        'empty_text_description' => NULL,
      ],
    ],
  ];
}

/**
 * Changes an exposed "type" filter from a multi-select to checkboxes.
 */
function mars_search_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  // Retrieve the view object and the query plugin.
  $storage = $form_state->getStorage();
  if (!isset($storage['view'])) {
    return;
  }
  $view = $storage['view'];
  if (!($view instanceof ViewExecutable)) {
    return;
  }
  // We need these values for the query.
  $form['search_api_fulltext']['#attributes']['data-mars-autocomplete'] = '1';
  $form['search_api_fulltext']['#attributes']['data-view_id'] = $view->id();
  $form['search_api_fulltext']['#attributes']['data-display_id'] = $view->current_display;
  // Container for autocomplete suggestions.
  $form['search_api_fulltext']['#suffix'] = '<div class="mars-suggestions"></div>';
  // Attaching javasript for autocomplete.
  $form['#attached']['library'][] = 'mars_search/autocomplete';
}
