<?php

/**
 * @file
 * Overrides to force a connection to Acquia search cores.
 */

/**
 * Alter the possible cores list.
 *
 * @param array $possible_core_ids
 *   The predefined list of possible cores.
 * @param array $context
 *   Context.
 *
 * @code
 *   $possible_core_ids = [
 *     'WXYZ-12345.prod.default',
 *     'WXYZ-12345.dev.mysitedev_folder1',
 *     'WXYZ-12345.dev.mysitedev_db',
 *   ];
 *   $context = [
 *     'ah_env' => 'dev',                // string|null
 *     'ah_db_role' => 'SomeDb1,         // string
 *     'identifier' => 'WXYZ-12345',     // string, may be empty
 *     'sites_foldername' => 'default',  // string
 *   ];
 * @endcode
 */
function pn_acquia_search_acquia_search_get_list_of_possible_cores_alter(array &$possible_core_ids, array $context) {
  // Retrieve dev-provided core IDs from config.
  $config = \Drupal::config('pn_acquia_search.settings');
  $config_cores = $config->get('possible_core_ids');
  if (!empty($config_cores)) {
    // Split the config data into an array on each new line.
    $override_core_ids = preg_split('/\R/', $config_cores);
    // Add dev-provided cores to the list used by the acquia_search module.
    $possible_core_ids = array_merge($possible_core_ids, $override_core_ids);
  }
}
