<?php

/**
 * @file
 * Primary module hooks for Mars Recommendations module.
 */

/**
 * Implements hook_theme().
 */
function mars_recommendations_theme($existing, $type, $theme, $path) {
  return [
    'recommendations_module_block' => [
      'variables' => [
        'title' => NULL,
        'graphic_divider' => NULL,
        'brand_border' => NULL,
        'recommended_items' => [],
        'text_color_override' => NULL,
      ],
      'template' => 'recommendations-module-block',
    ],
  ];
}
