theme_styles: "twix"
title: "TWIX® Cookies & Creme Bar"
image_src: "Recipe_Image.png"
products:
  - title: "Twix Cookies & Creme"
    id: "0001"
  - title: "Cookies & Creme"
    id: "0002"
  - title: "Twix Cookies"
    id: "0003"
  - title: "Creme"
    id: "0004"
  - title: "Twix Creme"
    id: "0005"
