theme_styles: 'twix'

eyebrow_text: 'PRODUCTS'
background_image_1: 'ellipse_4.svg'
background_image_2: 'ellipse_5.svg'
background_image_3: 'ellipse_6.svg'

heading_level: 1
heading: 'The Newest Member: Twix Cookies & Creme'
heading_url: 'https://storybook.js.org/'

default_link_content: 'Explore'
default_link_base_class: 'default-link'
default_link_border_radius: 30
default_link_attributes:
  'target': '_self'
  'href': 'https://storybook.js.org/'
