theme_styles: 'twix'

brand_shape: '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 200 200"><circle cx="100" cy="100" r="100"/></svg>'

eyebrow_text: 'PRODUCTS'
background_color: 'blue'

heading_level: 1
heading: 'The Newest Member: Twix Cookies & Creme'
heading_url: 'https://storybook.js.org/'
image_src: 'Bitmap@3x.png'
image_alt: 'Image alt text'

default_link_content: 'Explore'
default_link_base_class: 'default-link'
default_link_attributes:
  'target': '_self'
  'href': 'https://storybook.js.org/'
