mars_common.card_color_settings:
  type: config_object
  label: 'Card background color configuration'
  mapping:
    select_background_color_recipe:
      type: string
      label: 'Recipe card background color'
    select_background_color_product:
      type: string
      label: 'Product card background color'
    select_background_color_campaign:
      type: string
      label: 'Campaign card background color'
    select_background_color_landing:
      type: string
      label: 'Landing card background color'
    select_background_color_hub_card:
      type: string
      label: 'Content Hub card background color'
    select_background_color_article:
      type: string
      label: 'Article card background color'

block.settings.alertbanner_block:
  type: block_settings
  label: 'Mars Alert Banner Block'
  mapping:
    alert_banner:
      type: mapping
      label: 'Alert banner'
      mapping:
        alert_banner_text:
          type: mapping
          label: 'Alert banner text'
          mapping:
            value:
              type: string
              label: 'Field value'
            format:
              type: string
              label: 'Field format'
        alert_banner_url:
          type: label
          label: 'Alert banner URL'

block.settings.header_block:
  type: block_settings
  label: 'Mars Header Block'
  mapping:
    primary_menu:
      type: string
      label: 'Primary Menu'
    secondary_menu:
      type: string
      label: 'Secondary Menu'
    search_block:
      type: integer
      label: 'Search block'
    language_selector:
      type: integer
      label: 'Language Selector block'
    alert_banner:
      type: mapping
      label: 'Alert banner'
      mapping:
        alert_banner_text:
          type: mapping
          label: 'Alert banner text'
          mapping:
            value:
              type: string
              label: 'Field value'
            format:
              type: string
              label: 'Field format'
        alert_banner_url:
          type: label
          label: 'Alert banner URL'
        override_color_scheme:
          type: integer
          label: 'Override alert banner color'
        bg_color:
          type: string
          label: 'Background color'
        text_color:
          type: string
          label: 'Background color'
    override_text_color:
      type: mapping
      label: 'Override theme text color'
      mapping:
        override_color:
          type: integer
          label: 'Override color'
        —Åhoose_override_hover:
          type: integer
          label: 'Choose hover color'
        hover_color:
          type: string
          label: 'Override hover color'
        override_mobile_color:
          type: integer
          label: 'Override mobile header element colors'
        mobile_main_menu_items_color:
          type: string
          label: 'Override mobile menu color'
        mobile_cross_hamburger:
          type: string
          label: 'Override mobile cross/hamburher menu color'
        mobile_sub_menu_items_color:
          type: string
          label: 'Override mobile submenu items color'
        mobile_search_right_menu_section:
          type: string
          label: 'Override right menu section on mobile'

mars_common.emails_configuration:
  type: config_object
  label: 'Emails configuration'
  mapping:
    grocery_list_from:
      type: string
      label: 'FROM email'
    grocery_list_subject:
      type: label
      label: 'Grocery list email subject'
    grocery_list_body:
      type: text
      label: 'Grocery list email body'
    grocery_list_signature:
      type: text
      label: 'Grocery list email signature'
    recipe_from:
      type: string
      label: 'FROM email'
    recipe_subject:
      type: label
      label: 'Recipe email subject'
    recipe_body:
      type: text
      label: 'Recipe email body'
    recipe_signature:
      type: text
      label: 'Recipe email signature'
    default_langcode:
      type: string
      label: 'Site default language code'
