<?php

/**
 * @file
 * MARS Articles module main file.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;

/**
 * Implements hook_theme().
 */
function mars_articles_theme($existing, $type, $theme, $path) {
  return [
    'article_header_block_image' => [
      'variables' => [
        'label' => NULL,
        'eyebrow' => NULL,
        'publication_date' => NULL,
        'image' => NULL,
        'social_links' => NULL,
        'brand_borders' => NULL,
        'share_text' => NULL,
        'text_color_override' => NULL,
      ],
      'template' => 'block--mars-articles--header-image',
    ],
    'article_header_block_no_image' => [
      'variables' => [
        'label' => NULL,
        'eyebrow' => NULL,
        'publication_date' => NULL,
        'social_links' => NULL,
        'brand_borders' => NULL,
        'brand_shape' => NULL,
        'share_text' => NULL,
        'text_color_override' => NULL,
      ],
      'template' => 'block--mars-articles--header-no-image',
    ],
  ];
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function mars_articles_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() != 'node' || $bundle != 'article' || empty($base_field_definitions['title'])) {
    return $fields;
  }

  $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions['title'], $bundle);
  $field->setSetting('max_length', 60);
  $fields['title'] = $field;

  return $fields;
}
