onetrust.settings:
  type: config_object
  label: 'OneTrust settings'
  mapping:
    onetrust:
      type: mapping
      mapping:
        data_domain:
          type: text
          label: 'Data domain'
