<?php

/**
 * @file
 * MARS Recipe Feature module main file.
 */

/**
 * Implements hook_theme().
 */
function mars_recipe_feature_theme($existing, $type, $theme, $path) {
  return [
    'recipe_feature_block' => [
      'variables' => [
        'brand_borders' => NULL,
        'eyebrow' => NULL,
        'title' => NULL,
        'recipe_media' => [],
        'cooking_time' => NULL,
        'cta' => [],
      ],
      'template' => 'recipe-feature-block',
    ],
  ];
}
