<?php

/**
 * @file
 * MARS Common module main file.
 */

/**
 * Implements hook_theme().
 */
function mars_common_theme($existing, $type, $theme, $path) {
  return [
    'header_block' => [
      'variables' => [
        'logo' => NULL,
        'primary_menu' => NULL,
        'secondary_menu' => NULL,
        'language_selector' => NULL,
        'search_block' => NULL,
        'alert_banner' => NULL,
      ],
      'template' => 'block--mars-common--header',
    ],
    'footer_block' => [
      'variables' => [
        'logo'            => NULL,
        'twix_border'     => NULL,
        'social_links'    => NULL,
        'top_footer_menu' => NULL,
        'legal_links'     => NULL,
        'marketing'       => NULL,
        'corporate_tout'  => NULL,
        'region_selector' => NULL,
      ],
      'template' => 'footer-block',
    ],
    'content_feature_module_block' => [
      'variables' => [
        'eyebrow' => NULL,
        'label' => NULL,
        'background' => NULL,
        'description' => NULL,
        'explore_cta' => NULL,
        'explore_cta_link' => NULL,
      ],
      'template' => 'content-feature-module-block',
    ],
    'social_feed_block' => [
      'variables' => [
        'title' => '',
        'items' => [],
      ],
    ],
  ];
}
