theme_styles: 'twix'
title: 'Filter By:'
applied_filters_count: 3
applied_filters_list:
  - Nut Free
  - Cocoa For Generations
  - Bars/Countlines
items:
  - filter_title: 'Diet & Allergens'
    active_filters_count: 1
    checkboxes:
      - title: 'Gluten Free'
        key: 'gluten_free'
      - title: 'Non GMO Ingredients'
        key: 'non_gmo_ingredients'
      - title: 'No Artificial Flavors Or Preservatives'
        key: 'no_artificial_flavors_or_preservatives'
      - title: 'Dairy Free'
        key: 'dairy_free'
      - title: 'Nut Free'
        key: 'nut_free'
        checked: 'checked'
      - title: 'Soy Free'
        key: 'soy_free'
      - title: 'Shelfish Free'
        key: 'shelfish_free'
      - title: 'Kosher Certified'
        key: 'kosher_certified'
      - title: 'Vegetarian'
        key: 'vegetarian'
      - title: 'Vegan'
        key: 'vegan'
      - title: 'Halva'
        key: 'halva'

  - filter_title: 'Brand Initiatives'
    active_filters_count: 1
    checkboxes:
      - title: 'Bold Campaign'
        key: 'bold_campaign'
      - title: 'Cocoa For Generations'
        key: 'cocoa_for_generations'
        checked: 'checked'
      - title: 'Dove Cares'
        key: 'dove_cares'
      - title: 'Empowering Women'
        key: 'empowering_women'
      - title: 'Promises Wrappers'
        key: 'promises_wrappers'
      - title: 'Rainforest Alliance'
        key: 'rainforest_alliance'

  - filter_title: 'Format'
    active_filters_count: 1
    checkboxes:
      - title: 'Bars/Countlines'
        key: 'bars_countlines'
        checked: 'checked'
      - title: 'Bite Size'
        key: 'bite_size'
      - title: 'Mixed pack'
        key: 'mixed_pack'
      - title: 'Not Defined'
        key: 'not_defined'
      - title: 'Praline'
        key: 'praline'
      - title: 'Shapes'
        key: 'shapes'
      - title: 'Tablet'
        key: 'tablet'
