<?php

/**
 * @file
 * MARS Recipes module main file.
 */

/**
 * Implements hook_theme().
 */
function mars_recipes_theme($existing, $type, $theme, $path) {
  return [
    'recipe_detail_hero_block' => [
      'variables' => [
        'label' => NULL,
        'description' => NULL,
        'cooking_time' => NULL,
        'ingredients_number' => NULL,
        'number_of_servings' => NULL,
        'image' => NULL,
        'video' => NULL,
        'social_links' => NULL,
        'border' => NULL,
        'brand_shape_class' => NULL,
      ],
      'template' => 'block--mars-recipes--recipe-detail-hero',
    ],
    'recipe_detail_body_block' => [
      'variables' => [
        'ingredients_list' => NULL,
        'nutrition_module' => NULL,
        'product_used_items' => NULL,
      ],
      'template' => 'block--mars-recipes--recipe-detail-body',
    ],
    'recipe_feature_block' => [
      'variables' => [
        'brand_borders' => NULL,
        'brand_shape_class' => NULL,
        'eyebrow' => NULL,
        'title' => NULL,
        'recipe_media' => [],
        'cooking_time' => NULL,
        'cta' => [],
      ],
      'template' => 'block--mars-recipes--recipe-feature-block',
    ],
  ];
}
