<?php

/**
 * @file
 * MARS Recipes module main file.
 */

/**
 * Implements hook_theme().
 */
function mars_recipes_theme($existing, $type, $theme, $path) {
  return [
    'recipe_detail_hero_block' => [
      'variables' => [
        'label' => NULL,
        'description' => NULL,
        'cooking_time' => NULL,
        'ingredients_number' => NULL,
        'number_of_servings' => NULL,
        'image' => NULL,
        'video' => NULL,
        'social_links' => NULL,
      ],
      'template' => 'block--mars-recipes--recipe-detail-hero',
    ],
  ];
}
