<?php

/**
 * @file
 * MARS Recipes module main file.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function mars_recipes_theme($existing, $type, $theme, $path) {
  return [
    'recipe_detail_hero_block' => [
      'variables' => [
        'label' => NULL,
        'description' => NULL,
        'cooking_time' => NULL,
        'cooking_time_label' => NULL,
        'cooking_time_measure' => NULL,
        'ingredients_number' => NULL,
        'ingredients_label' => NULL,
        'ingredients_measure' => NULL,
        'number_of_servings' => NULL,
        'number_of_servings_label' => NULL,
        'number_of_servings_measure' => NULL,
        'image' => NULL,
        'video' => NULL,
        'social_links' => NULL,
        'border' => NULL,
        'custom_background_color' => NULL,
        'use_custom_color' => NULL,
        'brand_shape_enabled' => NULL,
        'brand_shape' => NULL,
        'social_text' => NULL,
      ],
      'template' => 'block--mars-recipes--recipe-detail-hero',
    ],
    'recipe_detail_body_block' => [
      'variables' => [
        'ingredients_list' => NULL,
        'nutrition_module' => NULL,
        'product_used_items' => NULL,
        'ingredients_used_label' => NULL,
        'products_used_label' => NULL,
      ],
      'template' => 'block--mars-recipes--recipe-detail-body',
    ],
    'recipe_feature_block' => [
      'variables' => [
        'brand_borders' => NULL,
        'block_title' => NULL,
        'graphic_divider' => NULL,
        'eyebrow' => NULL,
        'title' => NULL,
        'recipe_media' => [],
        'cooking_time' => NULL,
        'cta' => [],
      ],
      'template' => 'block--mars-recipes--recipe-feature-block',
    ],
  ];
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function mars_recipes_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() != 'node' || $bundle != 'recipe' || empty($base_field_definitions['title'])) {
    return $fields;
  }

  $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions['title'], $bundle);
  $field->setSetting('max_length', 60);
  $fields['title'] = $field;

  return $fields;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function mars_recipes_field_widget_form_alter(
  &$element,
  FormStateInterface $form_state,
  $context
) {
  $field_name = $context['items']->getName();

  $form_id = $form_state->getFormObject()->getFormId();
  $form_array = [
    'node_recipe_edit_form',
    'node_recipe_form',
  ];
  if (in_array($form_id, $form_array) && $field_name == 'field_recipe_cooking_time') {
    $element['value']['#step'] = 5;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function mars_recipes_preprocess_node__recipe__card(array &$variables) {
  $language_helper = \Drupal::service('mars_common.language_helper');
  $config = \Drupal::config('mars_common.site_labels');
  $variables['badge_text'] = $language_helper->translate($config->get('card_new_badge'));
  $variables['card_button_text'] = $language_helper->translate($config->get('recipe_card_button'));
}
